export const UserAuth = {
    USER_REGISTRATION_REQUEST : "USER_REGISTRATION_REQUEST",
    USER_REGISTRATION_SUCCESS : "USER_REGISTRATION_SUCCESS",
    USER_REGISTRATION_FAIL : "USER_REGISTRATION_SUCCESS",

    USER_LOGIN_REQUEST : "USER_LOGIN_REQUEST",
    USER_LOGIN_SUCCESS : "USER_LOGIN_SUCCESS",
    USER_LOGIN_FAIL : "USER_LOGIN_SUCCESS",

    USER_LOGOUT : "USER_LOGOUT",
}

export const TitleConstant = {
    TITLE_LIST_REQUEST : "TITLE_LIST_REQUEST",
    TITLE_LIST_SUCCESS : "TITLE_LIST_SUCCESS",
    TITLE_LIST_FAIL : "TITLE_LIST_FAIL",
    
    BOARD_ADD_REQUEST : "BOARD_ADD_REQUEST",
    BOARD_ADD_SUCCESS : "BOARD_ADD_SUCCESS",
    BOARD_ADD_FAIL : "BOARD_ADD_FAIL",

    BOARD_DELETE_REQUEST : "BOARD_DELETE_REQUEST",
    BOARD_DELETE_SUCCESS : "BOARD_DELETE_SUCCESS",
    BOARD_DELETE_FAIL : "BOARD_DELETE_FAIL",
}

export const CardConstant = {
    CARD_ADD_REQUEST : "CARD_ADD_REQUEST",
    CARD_ADD_SUCCESS : "CARD_ADD_SUCCESS",
    CARD_ADD_FAIL : "CARD_ADD_FAIL",

    CARD_UPDATE_REQUEST : "CARD_UPDATE_REQUEST",
    CARD_UPDATE_SUCCESS : "CARD_UPDATE_SUCCESS",
    CARD_UPDATE_FAIL : "CARD_UPDATE_FAIL",

    CARD_LIST_REQUEST : "CARD_LIST_REQUEST",
    CARD_LIST_SUCCESS : "CARD_LIST_SUCCESS",
    CARD_LIST_FAIL : "CARD_LIST_FAIL",

    CARD_DELETE_REQUEST : "CARD_DELETE_REQUEST",
    CARD_DELETE_SUCCESS : "CARD_DELETE_SUCCESS",
    CARD_DELETE_FAIL : "CARD_DELETE_FAIL",
}